### ISSUE TITLE
Recommend miniforge instead of miniconda?

### ISSUE THREAD

**Issue by adamgayoso** [scverse/cookiecutter-scverse#107]
https://github.com/scverse/cookiecutter-scverse/blob/c27563d1bd3901b71095b7e2c251ba16b4cc9127/%7B%7Bcookiecutter.project_name%7D%7D/README.md?plain=1#L21

**Comment by ivirshup** [comment]
Has anyone tried the mamba solver for conda? And is up to date on whether it's going to be the default?

--------

I think it's good to recommend conda since some users will use anaconda, and I don't think it's super obvious mamba is basically conda. But for sure could also recommend mamba.

**Comment by grst** [comment]
Miniforge != Mambaforge

It's just a conda distribution with conda forge channels set up properly, so I'm all for it.

**Comment by adamgayoso** [comment]
I think mambaforge is just miniforge where mamba is installed in the base env, so could also recommend this.

**Comment by Zethson** [comment]
Yeah, mambaforge would make sense.
Interestingly enough though I was able to run into environment solving issues with mamba at some point that worked with Conda. Their solver is slightly different and has some quirks. Way way faster though.
