### ISSUE TITLE
bump2version is useless :)

### ISSUE THREAD

**Issue by adamgayoso** [scverse/cookiecutter-scverse#115]
It changes a version in one file and adds an extra tedious step. Can we remove it?

**Comment by grst** [comment]
It also creates a git tag, fwiw

**Comment by adamgayoso** [comment]
so does github releases, which is easier to use

**Comment by grst** [comment]
I don't have a very strong opinion, but "just creating a github release" sounds like an easy way to forget bumping the version number in the code.

**Comment by flying-sheep** [comment]
Well I personally prefer using git metadata as a source of truth. I don’t see an advantage in having the version information duplicated somewhere else.

**Comment by grst** [comment]
Some people don't like it, so we decided not to use it as default, but describe in the docs how to enable hatch-vcs. 

@adamgayoso, you'd basically suggest one should manually edit the version in `pyproject.toml` and then create a tag/release? 

I think we all agree we should have automation for PyPI upload, there's #88 for that.

**Comment by adamgayoso** [comment]
>  you'd basically suggest one should manually edit the version in pyproject.toml and then create a tag/release?

Yes! This is how I've been doing it, and I have a github action for uploading to pypi once a release with a qualifying name is made (for example, via the github interface)

**Comment by grst** [comment]
fair enough. Do you want to submit a PR?

**Comment by flying-sheep** [comment]
would also be possible to create tags automatically pointing to

1. a commit
2. pushed to the default branch
3. changing the version in pyproject.toml
