### ISSUE TITLE
Error in pyproject.toml at initial pre-commit check

### ISSUE THREAD

**Issue by emdann** [scverse/cookiecutter-scverse#117]
Hi, I just made a new repo from the template with a dash in the project name (but no dash in the package name) and I get an error at the first pre-commit check.

After initializing the repo I just ran:
```
git add .
git commit -m 'init commit'
```
and autoflake check complained:
```python-traceback
Error: Could not open file '/nfs/team205/ed6/bin/patho-signatures/pyproject.toml': Error reading configuration file: Expected newline or end of document after a statement (at line 47, column 2)
```

The error comes from [this if statement](https://github.com/scverse/cookiecutter-scverse/blob/f19ba436fd40fa52382687a6a1030b1507c379fc/%7B%7Bcookiecutter.project_name%7D%7D/pyproject.toml#L49-L52) which ends up removing a new line in pyproject.toml:
```
test = [
    "pytest",
    "pytest-cov",
][tool.hatch.build.targets.wheel]
packages = ['src/pathosig']
```

It's easy to fix manually
```
test = [
    "pytest",
    "pytest-cov",
]

[tool.hatch.build.targets.wheel]
packages = ['src/pathosig']
``` 
but it might be worth fixing upstream.

**Comment by flying-sheep** [comment]
Thank you! I have a fix. We should add a unit test for that one.
