### ISSUE TITLE
Template sync fails when changes are made to workflow files

### ISSUE THREAD

**Issue by grst** [scverse/cookiecutter-scverse#138]
In a test-run, the template sync failed since apparently
the `sync.yaml` action is not permitted to make changes to files in the
`.github/workflows` directory:
https://github.com/icbi-lab/infercnvpy/actions/runs/3875431171/jobs/6607954535

This is a bit of a problem for which we still need to figure out a
solution. One of them is to use a personal access token. Another one
could be to centralize template sync, which I would have liked to avoid.

In #137, I roll back the changes made to workflow files since the last release,
as a short-term fix.

**Comment by Zethson** [comment]
Ohhh yeah I remember this. Think @imipenem and myself also ran into this some years back. We went for a PAT

**Comment by ivirshup** [comment]
We just had a bad problem with CI (see [discussion on zulip](https://scverse.zulipchat.com/#narrow/stream/316218-repo-management/topic/template.20sync/near/349042011)) and ended up needing to manually make the update PRs for 0.2.1. It would be nice to not have to do this.

@grst, could you go into some more detail on how the access token would work?

**Comment by grst** [comment]
* CI job runs in `cookiecutter-scverse` repo as cron job
 * list of repos using the template (either from search API or registry)
     - handle opt-out one way or another
 * for each repo, acting as `scverse-bot`
     - fork
     - clone
     - `cruft update`
     - create pull request
     
Here's a notebook doing that: https://gist.github.com/grst/d8d32f1d40b8dc84fd6fbe81d5df38c3

**Comment by ivirshup** [comment]
Where do we fork to, and where does the  clone happen? Can this happen on github actions, or would that also be blocked?

**Comment by grst** [comment]
- fork to `scverse-bot` (or we make a dedicated account, e.g. `scverse-template-update`). 
- This can absolutely happen on github actions (you just need to store the bot access token as a secret as we are already doing e.g. for syncing the `cookiecutter-scverse-instance` repo)

The difference is that
 - previously, the action ran *in the target repo*, i.e. the running action has access to repository secrets (therefore the restrictions)
 - now, we would be creating a fork. PRs from forks don't have access to secrets, therefore the restrictions don't apply.

**Comment by ivirshup** [comment]
Do either of you know how nf-core does this? It doesn't look like they make a fork.

* [nf-core sync docs](https://nf-co.re/developers/sync#introduction)
* Example of sync event: https://github.com/nf-core/rnaseq/pull/909

It's not super clear to me if the repository has to be under the nf-core organization for this to work though.

I'm trying to find the code for the nf-core bot, and how it's triggered.

**Comment by grst** [comment]
Afaik it's triggered upon a release of the `nf-core tools` package. And it only syncs repos within the `nf-core` organization using an access token that has commit rights to all repos.
