### ISSUE TITLE
`.cruft.json` contains hardcoded local path upon creation which causes `Sync template` action to fail

### ISSUE THREAD

**Issue by timtreis** [scverse/cookiecutter-scverse#140]
I created an empty repo yesterday which resultet in `.cruft.json` containing a local path -> https://github.com/scverse/spatialdata-plot/blob/main/.cruft.json

This causes the `Sync template` GH action to fail -> https://github.com/scverse/spatialdata-plot/actions/runs/3907895412

**Comment by timtreis** [comment]
Hm, yeah. that might be it. So I should just overwrite it with the GH link?

**Comment by grst** [comment]
yeah, that should work. 
Here's a `cruft.json` that works: https://github.com/icbi-lab/infercnvpy/blob/main/.cruft.json

**Comment by timtreis** [comment]
Thanks! I guess the `Sync template` action triggers at night?

**Comment by grst** [comment]
it does, but you can also trigger it manually via the Actions menu

**Comment by timtreis** [comment]
It actually still fails. Would you happen to know other locations where that path might've ended up? The GH search doesn't turn anything up for me

**Comment by timtreis** [comment]
odd? Okay, as long as it works, all good :D Thanks again!
