### ISSUE TITLE
Update developer docs

### ISSUE THREAD

**Issue by grst** [scverse/cookiecutter-scverse#17]
The developer docs of this template should contain everything that is not part of the scanpy deverloper docs we are linking from there. 

 - [ ] bump2version/release process
 - [x] setting up codecov
 - [ ] setting up pre-commit CI (compared to using github actions for it) 
 - [x] pre-commit
 - [ ] ...?

**Comment by giovp** [comment]
we have something here: https://github.com/theislab/squidpy/blob/master/CONTRIBUTING.rst useful?
