### ISSUE TITLE
Separate template documentation from packages' developer documentation

### ISSUE THREAD

**Issue by grst** [scverse/cookiecutter-scverse#173]
Right now we have `template_usage.md` and `contributing.md`. 
The former documents details about the template, the latter is targeted at developers of an actual package using the template. 

Currently, both documents are included in an instance of the template and rendered on readthedocs. 

I think we should exclude `template_usage` from instances. However, we then need a place where documentation for the template is hosted. Ideas: 

 * Just stick to github markdown files
 * find a way to **only** include it in the `cookiecutter-scverse-instance` repo, but not other instances
 * have another documentation website dedicated to the template

**Comment by grst** [comment]
We might be able to reduce our template documentation and link to the corresponding sections of the [pyOpenSci packaging guide](https://www.pyopensci.org/python-package-guide/package-structure-code/code-style-linting-format.html).

**Comment by flying-sheep** [comment]
> find a way to only include it in the cookiecutter-scverse-instance repo, but not other instances

that should be pretty easy actually, and doesn’t have the drawbacks the other two approaches have

we just need to define a [variable that doesn’t get shown to the user](https://cookiecutter.readthedocs.io/en/stable/advanced/private_variables.html) and override it when rendering in the instance repo.
