### ISSUE TITLE
images in tutorials are rendered too large if not constrained by page width

### ISSUE THREAD

**Issue by grst** [scverse/cookiecutter-scverse#192]
![image](https://github.com/scverse/cookiecutter-scverse/assets/7051479/d9159d6b-6ba4-4ef2-b888-7f7f7829a8ea)

**Comment by flying-sheep** [comment]
Matplotlib is configured to use a high DPI, and [communicates the metadata](https://github.com/scverse/scirpy/blob/1f3eb33d021bf3d15b0c484912e522f5ac01ff8f/docs/tutorials/tutorial_io.ipynb?short_path=c9f1766#L733-L747) about “CSS pixels” via Jupyter cell metadata.

```json
{
  "data": {
    "image/png": "…",
    "text/plain": ["<Figure size 480x480 with 1 Axes>"]
  },
  "metadata": {
    "image/png": {
      "height": 398,
      "width": 390
    }
  },
  "output_type": "display_data"
}
```

It looks like myst-nb [adds that metadata to the image node](https://github.com/executablebooks/MyST-NB/blob/752d20f83458535c435b7d8169ab11ad88f575d0/myst_nb/core/render.py#L667-L681), but somehow it doesn’t end up in the `<img>` tag.

A possible cause might be that the metadata is unitless and might be an int. Maybe myst-nb adding `px` to unitless `width` or `height` would work? [docutils says](https://docutils.sourceforge.io/docs/ref/rst/directives.html#image) it wants a “length” or “percentage”, which maybe has to be a string with “px” or “%” at the end

**Comment by grst** [comment]
This has been fixed. TODO: require myst-nb>=v1.1.0 in the template.
