### ISSUE TITLE
Template sync fails

### ISSUE THREAD

**Issue by lauradmartens** [scverse/cookiecutter-scverse#194]
Thanks a lot for the cool template! 
I experience problems with the template sync. It fails on the `Create pull request`: https://github.com/theislab/transcription_factor_activity/actions/runs/5128187970

**Comment by grst** [comment]
Hi Laura, 

we are aware of the issue, see https://github.com/scverse/cookiecutter-scverse/issues/138. 
The solution we came up with is to centralize the synchronisation, i.e. there will not be a github action in your repo anymore, but instead @scverse-bot will make PRs to your repo.

We have been working on this at the last hackathon, but haven't rolled it out yet. See https://github.com/scverse/cookiecutter-scverse/pull/168. 

For now, you can just delete the `sync.yaml` in your repo. Once we merged #168, you will anyway receive updates again. 
You can also manually update the repo by using the `cruft update` command. 

Cheers, 
Gregor
