### ISSUE TITLE
Finish centralized template sync

### ISSUE THREAD

**Issue by flying-sheep** [scverse/cookiecutter-scverse#208]
- [x] make cruft use the release tag instead of `main`
- [x] install pre-commit in GH workflow to run`pre-commit autoupdate` successfully
- [x] fix fork support:
  - make the workflow clone into namespaced directories (e.g. `~/original-author/reponame`, `~/forking-user/reponame`)
  - make the branch contain the user name (e.g. `original-author-template-update-v3.7`)
- ~~[ ] make cruft runs and PR generations run in parallel (so waiting for GH happens in parallel)~~
- [ ] fix tests and merge PR

**Comment by grst** [comment]
I don't want to go for parallel at the moment. It's already reasonably fast  (few minutes for ~30 repos) and parallel workflows are significantly harder to debug and reason about. 

We can reconsider that once we reach a couple of hundred repos. 

The rest is addressed in #222
