### ISSUE TITLE
Is it possible to execute the CI on the newly generated package? 

### ISSUE THREAD

**Issue by grst** [scverse/cookiecutter-scverse#21]
I.e. dynamically launch a github action based on the yaml file generated by cookiecutter.

**Comment by giovp** [comment]
I think this is what happens already no?

**Comment by grst** [comment]
The idea was to go one step further and test the *generated* github actions script. 

Currently we do run the tests and precommit, but using the CI script from the template repo.

**Comment by flying-sheep** [comment]
I see two options:

1. https://github.com/nektos/act
2. make the template’s workflow create a branch with the final code in it. Configure GH actions to run on that branch. Probably hard to communicate back that branch’s CI state to the original run

**Comment by grst** [comment]
I think @ivirshup's comment in https://github.com/scverse/cookiecutter-scverse/issues/22#issuecomment-1116423859 actually better fits here: 

> 
> It looks like cookiecutter-hypermodern-python uses a second [cookiecutter-hypermodern-python-instance](https://github.com/cjolowicz/cookiecutter-hypermodern-python-instance) repo for running the generated tests. See:
> 
> https://github.com/cjolowicz/cookiecutter-hypermodern-python/blob/ce04c553fb4c6786b97ce5401f6e3fada64bf0f1/.github/workflows/update-instance.yml#L39-L44

I quite like the idea of having an "instance" repo. It allows people to browse how the final structure would look like and also provide a preview for docs etc. 

CI tests could also be run there, but I doubt there would be an easy way of getting checkmarks for that in a pull request.

**Comment by ivirshup** [comment]
> CI tests could also be run there, but I doubt there would be an easy way of getting checkmarks for that in a pull request.

@michalk8, is this possible?

**Comment by michalk8** [comment]
> @michalk8, is this possible?

Maybe this could be used: https://github.com/nektos/act (for running actions locally)
Alternatively, having a dummy repo containing the instantiated template that gets synced on PRs in this might be a cleaner solution, but also more engineering.

**Comment by flying-sheep** [comment]
I think @ivirshup meant propagating the status from the “instance repo”’s runs to this repo’s runs.

I already mentioned act above. It might work, but it doesn’t support all workflows.

**Comment by ivirshup** [comment]
Pretty much. I'm thinking we would copy the setup from [this cookie cutter template](https://github.com/cjolowicz/cookiecutter-hypermodern-python/blob/ce04c553fb4c6786b97ce5401f6e3fada64bf0f1/.github/workflows/update-instance.yml#L39-L44)

Ideally we could also get a check here for CI from the instance passing, but idk if that's possible.

**Comment by grst** [comment]
Is anyone opposed to setting up an instance repo? I could give it a try [maybe next week]. 

We could basically mirror the entire branch structure of this repo in the instance repo. That would allow to preview feature branches as well.
