### ISSUE TITLE
Run pre-commit CI on the main repo

### ISSUE THREAD

**Issue by grst** [scverse/cookiecutter-scverse#22]

**Comment by ivirshup** [comment]
It looks like cookiecutter-hypermodern-python uses a second [cookiecutter-hypermodern-python-instance](https://github.com/cjolowicz/cookiecutter-hypermodern-python-instance) repo for running the generated tests. See: 

https://github.com/cjolowicz/cookiecutter-hypermodern-python/blob/ce04c553fb4c6786b97ce5401f6e3fada64bf0f1/.github/workflows/update-instance.yml#L39-L44

**Comment by ivirshup** [comment]
Should we close this, since it's a subtask of #21?

We have pre-commit running, and I think it's trivial to get that CI task running once CI for the generated repo exists

**Comment by grst** [comment]
We need better terminology to distinguish between template and non template code :sweat_smile: 

With this issue I meant running the root-level pre-commit on CI:
https://github.com/scverse/cookiecutter-scverse/blob/main/.pre-commit-config.yaml

I think we are doing this via `pre-commit-ci` already, therefore, I close the issue.

**Comment by ivirshup** [comment]
haha yeah
