### ISSUE TITLE
Create separate Github Actions workflows for build/task/(publish)

### ISSUE THREAD

**Issue by Zethson** [scverse/cookiecutter-scverse#27]
Currently they are all in `test.yml`

**Comment by ivirshup** [comment]
@giovp @flying-sheep 

I'm a little confused about what the state of the generated projects github actions is. It looks like a PR got merged prematurely but not sure what was left to be added.

I think the CI job should be split. Currently is one job that does pre-commit, tests, and docs. These should be handled separately. I also think the docs should be handled by readthedocs, not github actions.

**Comment by ivirshup** [comment]
Also, it looks like the build check got deleted

**Comment by giovp** [comment]
only thing afaik I had to do on pre-commit side was to add it to CI which indeed is still left to be done

> Also, it looks like the build check got deleted

not sure it was from our side

**Comment by grst** [comment]
> It looks like a PR got merged prematurely but not sure what was left to be added.

IDK, but it seems to be ok now (separate test and build action, both doing what they are supposed to do)
