### ISSUE TITLE
Switch to src/ layout

### ISSUE THREAD

**Issue by flying-sheep** [scverse/cookiecutter-scverse#28]
See here for places recommending it:

- PyPA [discussion](https://github.com/pypa/packaging.python.org/issues/320#issuecomment-495990983), [protocol](https://docs.google.com/document/d/1Wz2-ECkicJgAmQDxMFivWmU2ZunKvPZ2UfQ59zDGj7g/edit#heading=h.2cgqnlxl8y3e)

  (Note that “single module” uses official terminology in which “module” means `x.is_file() and x.suffix == '.py'` and  “package” means `x.is_dir() and x.join('__init__.py').is_file()`.)

- [Ionel’s blog](https://blog.ionelmc.ro/2014/05/25/python-packaging/#the-structure)
- [Hypermodern Python](https://cjolowicz.github.io/posts/hypermodern-python-01-setup/#creating-a-package-in-src-layout) defers to [Hynek’s blog](https://hynek.me/articles/testing-packaging/)

Furthermore I think:

- The symmetry makes sense: `ls *(/)` will yield `src` `tests` `docs`, package specific names start appearing inside of those
- adding `{project}/src` to PYTHONPATH or doing `pip install -e .` is safer than adding `{project}`

(Resolution: Try it out after all PRs touching the code got merged)

**Comment by flying-sheep** [comment]
Since finding the discussion, I also found that both the Hypermodern Python package guide and Ionel’s blog (i.e. all places that I found that gives reasons for choosing a layout) picked this one.

**Comment by ivirshup** [comment]
It may not have been clear due to the hybrid meeting (which we definitely didn't prepare well for), but I think everyone else was against this. I think I'm going to revert this, though we can always add  it if it gets some support.

**Comment by flying-sheep** [comment]
You said “let’s try it”.

**Comment by ivirshup** [comment]
Ah yeah, so what I had meant there (and I think was in response to others) was: "lets try it out for a project before making it a part of the template".

**Comment by flying-sheep** [comment]
Aah, I see! How far did you get with the stats package yesterday?

**Comment by flying-sheep** [comment]
The more I read about it the more convinced I become: https://setuptools.pypa.io/en/latest/userguide/package_discovery.html#src-layout

**Comment by grst** [comment]
> It seems unnecessary and reminded me of Java

That was exactly my feeling, but Hynek makes a few good points. 

I think I'm slightly in favor of `src` now, but the question remains whether it's worth the effort changing something.

**Comment by flying-sheep** [comment]
> whether it's worth the effort changing something

I don’t think I understand what kind of change you’re referring to.

For the code changes it’s `mkdir src; git mv '{{cookiecutter.package_name}}' src/`

And what other kind of change is there?

**Comment by grst** [comment]
I guess it would imply that at some point would want to update all scverse
core packages

**Comment by grst** [comment]
Done in #79
