### ISSUE TITLE
Social cards do not support svg

### ISSUE THREAD

**Issue by jeskowagner** [scverse/cookiecutter-scverse#339]
While building docs with `hatch run docs:build` I get many warnings of the type:
`WARNING: [Social card] image cannot be an SVG image, skipping...`
Like `scanpy`, I use a `svg` logo. I don't see the social card being used anywhere in the RTD, so can one somehow skip the generation of it? I am unsure why card generation is attempted in the first place, given that it's not imported explicilty in `docs/conf.py`. I don't see it being used in `sphinx_book_theme` either.

**Comment by flying-sheep** [comment]
> I don't see the social card being used anywhere in the RTD

That’s not where it shows up. It shows up when someone links to your docs from social media (i.e. it becomes an embed picture on e.g. Discord, Reddit, or Slack).

> I am unsure why card generation is attempted in the first place

It comes from [`sphinxext-opengraph`](https://pypi.org/project/sphinxext-opengraph/): https://github.com/scverse/cookiecutter-scverse/blob/5d44c58df427f884585ae9772cae81f1b6638f80/%7B%7Bcookiecutter.project_name%7D%7D/docs/conf.py#L61C6-L61C25

If you search in [its docs](https://sphinxext-opengraph.readthedocs.io/en/latest/), you’ll find a a broken link under the description for `ogp_social_cards`. That link is supposed to go to this subpage: https://sphinxext-opengraph.readthedocs.io/en/latest/socialcards.html

**Comment by jeskowagner** [comment]
Thanks for the pointers, very helpful! With it I understood how to redirect the image to be a `png` [as instructed](https://sphinxext-opengraph.readthedocs.io/en/latest/socialcards.html#id2). Cheers!

**Comment by flying-sheep** [comment]
Glad I could help!
