### ISSUE TITLE
Prettier mirror is archived

### ISSUE THREAD

**Issue by jeskowagner** [scverse/cookiecutter-scverse#341]
See the notice on: https://github.com/pre-commit/mirrors-prettier
It's currently used in the GH actions.

**Comment by grst** [comment]
There's already some discussion here: https://github.com/scverse/cookiecutter-scverse/issues/283

But maybe we'll need a short-term solution.

**Comment by jeskowagner** [comment]
My bad, closing here in favor of that issue. Thanks!
