### ISSUE TITLE
cookietemple

### ISSUE THREAD

**Issue by grst** [scverse/cookiecutter-scverse#35]
It probably makes sense to wait until the development of the template has slowed down a bit, but eventually I would absolutely like to jave template sync.

**Comment by ivirshup** [comment]
<details>
<summary> My notes: </summary>

- cookietemple package
    - Must live in cookietemple
- cookietemple-lint (scope is similar to precommit)
    - Versioning system
- bump-version
    - Could be split out
    - Checks that things are possible
- Sync
    - [https://github.com/cookiejar/cookietemple/blob/development/cookietemple/create/templates/cli/cli_python/{{ cookiecutter.project_slug_no_hyphen }}/cookietemple.cfg](https://github.com/cookiejar/cookietemple/blob/development/cookietemple/create/templates/cli/cli_python/%7B%7B%20cookiecutter.project_slug_no_hyphen%20%7D%7D/cookietemple.cfg)
    - Authors entry won’t be updated right
    - Template file with default values [https://github.com/theislab/ehrapy/blob/development/.cookietemple.yml](https://github.com/theislab/ehrapy/blob/development/.cookietemple.yml)
- Cookie temple wish list
    - default branch
    - config values
        - author
    - Is the template branch neccesary
    - bump-version? Could run bump2version

</details>

Main takeaways were:

* Figure out overlap b/w our pre-commit setup and cookietemple lint
* Figure out how rough sync diffs will be, as some templated values are expected to change
  * Figure out why sync uses a template branch
* bump2version vs cookietemple-bumpversion

**Comment by grst** [comment]
Here's another repo using `cruft` for this: 
https://github.com/woltapp/wolt-python-package-cookiecutter/blob/6669a067eeaaed3bee84312428a3e94cd13295f2/%7B%7Bcookiecutter.project_slug%7D%7D/.github/workflows/cookiecutter.yml
