### ISSUE TITLE
feedback from first usage

### ISSUE THREAD

**Issue by giovp** [scverse/cookiecutter-scverse#41]
- [x] authro email etc is still @ivirshup account
- [x] request for organization name yet it's better to say organization/user imho
- [ ] is pre-commit not installed, it fails after all the prompts, should fail earlier
- [ ] pre-commit is not separate job in the generated repo

**Comment by ivirshup** [comment]
> authro email etc is still ivirshup account

This seems quite common in cookie cutter templates

> request for organization name yet it's better to say organization/user imho

Could call it `github_user` instead of github org?

**Comment by giovp** [comment]
> Could call it github_user instead of github org

better imho

**Comment by grst** [comment]
This has been fixed in #48 I think
