### ISSUE TITLE
remove failing test form CI?

### ISSUE THREAD

**Issue by giovp** [scverse/cookiecutter-scverse#44]
https://github.com/scverse/cookiecutter-scverse/blob/92c74be6dd2e1619151346ed48da6cdf3abcbe94/%7B%7Bcookiecutter.project_name%7D%7D/tests/test_basic.py#L9

**Comment by flying-sheep** [comment]
I think we can just skip that specific test when running tests for the instantiated project. That way we can check if the tests of that project run in general while still teaching people to write tests.
