### ISSUE TITLE
Pre-commit cache for CI

### ISSUE THREAD

**Issue by ivirshup** [scverse/cookiecutter-scverse#50]
This is downloading and installing all the pre-commits every single time. It should cache them instead.

**Comment by flying-sheep** [comment]
A feature we get for free with pre-commit.ci

**Comment by ivirshup** [comment]
Can that for the generated instance?

**Comment by grst** [comment]
The developer using the template would need to connect the pre-commit CI service. If their organization has set this up, it will run automatically. 

Could add this step to the documentation (they anyway need to connect the codecov and readthedocs services, not a big deal if there's one more...)

**Comment by grst** [comment]
The pre-commit action we currently have
 * isn't actively maintained anymore
 * doesn't autocommit
 * doesn't have caching
 * is slower than pre-commit.ci. 

#84 removes that action. #81 adds documentation how to enable pre-commit.ci for the repo.
