### ISSUE TITLE
Syncing to currently existing repo

### ISSUE THREAD

**Issue by ilibarra** [scverse/cookiecutter-scverse#55]
What could be a recommended series of steps for linking cookiecutter-scverse to a currently existing package, with previous commits and code?

e.g. create a branch, including all the default code and then PR to main could work for this purpose, or another way to maintain the previous log of commits.

Thanks for any input on this.

**Comment by Zethson** [comment]
Hey,

I guess that what you suggested is the way to go.
1. Create a new branch
2. Create the project with the template
3. Copy the existing files into the template. This ensures that they have the same git hash
4. Push to your branch.
5. PR against your main branch.
