### ISSUE TITLE
Fixit

### ISSUE THREAD

**Issue by flying-sheep** [scverse/cookiecutter-scverse#56]
We said we prefer autofixes to nitpicking.

There’s https://github.com/Instagram/Fixit, ~~but it doesn’t have~~ which as of 2023-01-24 has a pre-commit hook

**Comment by ivirshup** [comment]
This would only come up if we want to add custom fixes, right?

**Comment by grst** [comment]
How does this relate to ruff (#142). Do we need both?

**Comment by flying-sheep** [comment]
We don’t, Ruff has autofix capabilities. As we switched to Ruff, this can be closed.
