### ISSUE TITLE
Create issue templates

### ISSUE THREAD

**Issue by grst** [scverse/cookiecutter-scverse#57]
I think this repo should provide sensible default issue templates and link to the scverse discourse for help requests.

**Comment by grst** [comment]
I tried setting that up for scirpy. Feedback welcome!

https://github.com/scverse/scirpy/issues/new/choose

 * One issue I'm having is that I didn't find a way to make the version info collapsible. Either there's still some need for a markdown template within the form, or it won't be collapsed. 

Once we are happy with it there, I'll copy it over to this repo.

**Comment by grst** [comment]
Link to a demo bug report: 
https://github.com/scverse/scirpy/issues/340

The section *Version Information* is quite unusable atm... maybe better to just use a plain text field. This might result in a very long issue, but :shrug:

**Comment by Zethson** [comment]
Great!

"plase paste the output between the backticks "

Typo

I'm a fan of the background text that you have in the other cells. Maybe this would also be something for the version information?
But this seems to be a decent version
![image](https://user-images.githubusercontent.com/21954664/169498695-5ee67db1-d295-46c2-b695-1ad3f579357c.png)

Not collapsible, but I don't know how to make that work either.

**Comment by grst** [comment]
Yeah, I think I'm gonna get rid of the template for making it collapsible.

Should we still advertise for putting the full list of versions returned by
`sc.logging.print_versions()` or rather ask for a few specific ones (the
package itself and maybe numpy/pandas)?

**Comment by Zethson** [comment]
Not sure whether all of our ecosystem packages require scanpy as a dependency. Some people may not know where this command comes from. I'd go with a "manual" approach (what you suggested)

**Comment by grst** [comment]
New version: https://github.com/scverse/scirpy/blob/9665b2d5d011ce1df230809050c800f264dba095/.github/ISSUE_TEMPLATE/bug_report.yml

**Comment by Zethson** [comment]
MuData version might also be relevant. Maybe we should ask users to run https://pypi.org/project/session-info/ ? This might be the most general version.

**Comment by ivirshup** [comment]
[`sc.logging.print_versions()`](https://github.com/scverse/scanpy/blob/bd06cc3d1e0bd990f6994e54414512fa0b25fea0/scanpy/logging.py#L161) is just `session-info`.

Lesson learned from scanpy: get people to report all imported packages in the session where the bug occurred. This will save many hours of debugging.

**Comment by ivirshup** [comment]
Stuff eventually got fixed, but there is also https://github.com/IBM/import-tracker (which I haven't tried)

**Comment by grst** [comment]
Another one
https://pypi.org/project/depinfo/
