### ISSUE TITLE
Tests fail on warning

### ISSUE THREAD

**Issue by ivirshup** [scverse/cookiecutter-scverse#65]
Tests probably shouldn't fail on warnings being thrown.

**Comment by grst** [comment]
This is set-up in `pyproject.toml`:

https://github.com/scverse/cookiecutter-scverse/blob/62c8253de2de268fe15d8fe1b64e132a0fa925a9/%7B%7Bcookiecutter.project_name%7D%7D/pyproject.toml#L56-L62

It seems @flying-sheep  put this on purpose. Do we want to keep it? 

As usual, mandating no warnings is a tradeoff between being annoyed now vs possibly being annoyed later if something breaks :shrug:
