### ISSUE TITLE
Do we need a setup function for building docs?

### ISSUE THREAD

**Issue by ivirshup** [scverse/cookiecutter-scverse#70]
Unclear to me what this is for:

https://github.com/scverse/cookiecutter-scverse/blob/fb25fef4eb7ef66b37040684698ba7a15efa0af6/%7B%7Bcookiecutter.project_name%7D%7D/docs/conf.py#L98-L110

**Comment by adamgayoso** [comment]
Same here, do we need this?

**Comment by grst** [comment]
No idea. What happens if we remove it? 

@michalk8 added this I think.
