### ISSUE TITLE
Add action for publish/upload on PyPI

### ISSUE THREAD

**Issue by grst** [scverse/cookiecutter-scverse#88]
... or at least show in the docs how to set one up. 

(initially suggested in #27, but that issue was about something else)

**Comment by Zethson** [comment]
Example: https://github.com/theislab/ehrapy/blob/development/.github/workflows/publish_package.yml

Need to replace the poetry build with the general build command and we're good to go. Need to add docs for the PyPI token

**Comment by adamgayoso** [comment]
https://github.com/YosefLab/scib-metrics/blob/main/.github/workflows/release.yaml

**Comment by ivirshup** [comment]
I would vote for showing how to do one over including the action.

Any idea how publishing via CI interacts with 2FA? pypa has been pushing for 2FA on uploads recently, and it will be required for anndata in the future.

**Comment by giovp** [comment]
> Any idea how publishing via CI interacts with 2FA? pypa has been pushing for 2FA on uploads recently, and it will be required for anndata in the future.

interesting, but isn't 2FA only for critical projects (likely not newly generated projects with this template)?

> I would vote for showing how to do one over including the action.

agree it's also a great pedagogical example
